#!/usr/bin/env bash
# =============================================================================
# install-sink.sh — Install or update Sink on VPS
# =============================================================================
# Location on VPS: /opt/infra/apps/sink/install-sink.sh
#
# This script:
#   1. Creates the application directory structure
#   2. Clones (or pulls) the Sink repository
#   3. Validates that .env exists
#   4. Generates production compose.yml and nginx proxy config
#   5. Builds images and runs Prisma migrations
#   6. Starts all services (api, web, nginx)
#   7. Verifies service health
#
# Usage:
#   cd /opt/infra/apps/sink
#   chmod +x install-sink.sh
#   ./install-sink.sh
#
# For updates, use update.sh instead.
#
# Prerequisites:
#   - Docker and Docker Compose installed
#   - PostgreSQL accessible from the VPS (cloud-hosted or local)
#   - .env file with production values
# =============================================================================
set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
SINK_DIR="/opt/infra/apps/sink"
REPO_DIR="${SINK_DIR}/repo"
REPO_URL="https://github.com/marinoscar/sink.git"
BRANCH="main"
DOMAIN="sink.dev.marin.cr"
HOST_PORT="8321"

log() { echo "[sink] $*"; }

# ---------------------------------------------------------------------------
# Step 1: Create directory structure
# ---------------------------------------------------------------------------
log "============================================"
log " Sink Installer"
log "============================================"
log ""
log "[1/7] Setting up directories..."

mkdir -p "${SINK_DIR}"

log "  Directories ready."

# ---------------------------------------------------------------------------
# Step 2: Clone or pull the repository
# ---------------------------------------------------------------------------
log ""
log "[2/7] Fetching source code..."

if [ -d "${REPO_DIR}/.git" ]; then
    log "  Repository exists. Pulling latest from ${BRANCH}..."
    cd "${REPO_DIR}"
    git fetch origin
    git reset --hard "origin/${BRANCH}"
    cd "${SINK_DIR}"
    log "  Updated to latest."
else
    log "  Cloning from ${REPO_URL}..."
    git clone --branch "${BRANCH}" "${REPO_URL}" "${REPO_DIR}"
    log "  Clone complete."
fi

# ---------------------------------------------------------------------------
# Step 3: Check .env exists
# ---------------------------------------------------------------------------
log ""
log "[3/7] Checking environment file..."

if [ ! -f "${SINK_DIR}/.env" ]; then
    log ""
    log "  ERROR: .env file not found at ${SINK_DIR}/.env"
    log ""
    log "  Create it from the template:"
    log "    cp ${REPO_DIR}/infra/compose/.env.example ${SINK_DIR}/.env"
    log "    nano ${SINK_DIR}/.env"
    log ""
    log "  Required values to set:"
    log "    - COMPOSE_PROJECT_NAME=sink"
    log "    - NODE_ENV=production"
    log "    - APP_URL=https://${DOMAIN}"
    log "    - POSTGRES_HOST (your PostgreSQL hostname)"
    log "    - POSTGRES_PASSWORD"
    log "    - POSTGRES_SSL=true (if using cloud PostgreSQL)"
    log "    - JWT_SECRET (generate with: openssl rand -hex 32)"
    log "    - COOKIE_SECRET (generate with: openssl rand -hex 32)"
    log "    - GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET"
    log "    - GOOGLE_CALLBACK_URL=https://${DOMAIN}/api/auth/google/callback"
    log "    - S3_BUCKET, S3_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY"
    log "    - CALENDAR_ENCRYPTION_KEY (generate with: openssl rand -hex 32)"
    log "    - INITIAL_ADMIN_EMAIL"
    log ""
    log "  Then run this script again."
    exit 1
fi

log "  .env file found."

# ---------------------------------------------------------------------------
# Step 4: Generate production compose.yml and proxy config
# ---------------------------------------------------------------------------
log ""
log "[4/7] Generating production configuration..."

# ---- compose.yml ----
# Production-ready Docker Compose file that:
#   - Binds nginx to 127.0.0.1:8321 (VPS proxy routes here)
#   - API connects to PostgreSQL over the network (via env vars)
#   - Uses an internal sink-internal network for service-to-service
#   - Uses the production nginx config (web:80 upstream)
#   - Sets restart policies and resource limits

cat > "${SINK_DIR}/compose.yml" << 'COMPOSE_EOF'
# =============================================================================
# Sink — Production Docker Compose
# =============================================================================
# Generated by install-sink.sh
# Do not edit manually — re-run the installer to regenerate.
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # Nginx — Internal reverse proxy (routes /api → api, / → web)
  # ---------------------------------------------------------------------------
  nginx:
    container_name: sink-nginx
    image: nginx:alpine
    ports:
      - "127.0.0.1:8321:80"
    volumes:
      - ./repo/infra/nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - web
    restart: unless-stopped
    networks:
      - sink-internal

  # ---------------------------------------------------------------------------
  # API — NestJS Backend (Fastify)
  # ---------------------------------------------------------------------------
  api:
    container_name: sink-api
    build:
      context: ./repo/apps/api
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
    networks:
      - sink-internal

  # ---------------------------------------------------------------------------
  # Web — React Frontend (static build served by Nginx)
  # ---------------------------------------------------------------------------
  web:
    container_name: sink-web
    build:
      context: ./repo/apps/web
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      - sink-internal

# =============================================================================
# Networks
# =============================================================================
networks:
  # Internal network for service-to-service communication
  sink-internal:
    driver: bridge
COMPOSE_EOF

log "  compose.yml generated."

# ---- VPS proxy nginx config ----
# This file goes into /opt/infra/proxy/nginx/conf.d/ to route
# sink.dev.marin.cr traffic to the sink-nginx container.

cat > "${SINK_DIR}/sink.conf" << NGINX_EOF
# =============================================================================
# sink.dev.marin.cr — VPS Reverse Proxy Config
# =============================================================================
# Generated by install-sink.sh
# Copy to: /opt/infra/proxy/nginx/conf.d/sink.conf
# =============================================================================

server {
    listen 443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/dev.marin.cr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/dev.marin.cr/privkey.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Allow large request bodies (file uploads, calendar JSON)
    client_max_body_size 50m;

    # API routes
    location /api {
        proxy_pass http://127.0.0.1:${HOST_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_connect_timeout 60s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
    }

    # Frontend (React SPA)
    location / {
        proxy_pass http://127.0.0.1:${HOST_PORT};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name ${DOMAIN};

    # ACME challenge (Let's Encrypt)
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$server_name\$request_uri;
    }
}
NGINX_EOF

log "  sink.conf generated."

# ---------------------------------------------------------------------------
# Step 5: Build images and run migrations
# ---------------------------------------------------------------------------
log ""
log "[5/7] Building images..."

cd "${SINK_DIR}"
docker compose build

log "  Images built."

log ""
log "  Running database migrations..."

# Source .env to get database connection parameters
set -a
. "${SINK_DIR}/.env"
set +a

# URL-encode the password (handles special characters like ! @ # etc.)
ENCODED_PW=$(python3 -c "import urllib.parse; print(urllib.parse.quote('${POSTGRES_PASSWORD}', safe=''))")

DATABASE_URL="postgresql://${POSTGRES_USER}:${ENCODED_PW}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
if [ "${POSTGRES_SSL:-false}" = "true" ]; then
    DATABASE_URL="${DATABASE_URL}?sslmode=require"
fi

docker compose run --rm -T -e DATABASE_URL="${DATABASE_URL}" api sh -c \
    "npx prisma migrate deploy"

log "  Migrations complete."

log "  Running database seeds..."

docker compose run --rm -T -e DATABASE_URL="${DATABASE_URL}" -e INITIAL_ADMIN_EMAIL="${INITIAL_ADMIN_EMAIL}" api sh -c \
    "npx prisma db seed"

log "  Seeds complete."

# ---------------------------------------------------------------------------
# Step 6: Start all services
# ---------------------------------------------------------------------------
log ""
log "[6/7] Starting all services..."

docker compose up -d

log "  All containers started."

# Wait for API to be ready
log "  Waiting for API to initialize..."
API_READY=false
for i in $(seq 1 60); do
    if docker exec sink-api wget -qO- http://localhost:3000/api/health/live >/dev/null 2>&1; then
        API_READY=true
        break
    fi
    sleep 2
done

if [ "${API_READY}" = "false" ]; then
    log "  WARNING: API health check did not pass within 120 seconds."
    log "  Check logs: docker compose logs api"
fi

# ---------------------------------------------------------------------------
# Step 7: Verify health
# ---------------------------------------------------------------------------
log ""
log "[7/7] Verifying services..."
sleep 3

# Check containers are running
RUNNING=$(docker compose ps --format '{{.Name}}' 2>/dev/null | wc -l)
log "  Containers running: ${RUNNING}"

# Check API health
API_STATUS=$(docker exec sink-api wget -qO- http://localhost:3000/api/health/live 2>/dev/null || echo "FAIL")
if echo "${API_STATUS}" | grep -qi "ok\|status\|healthy"; then
    log "  API health:    OK"
else
    log "  API health:    WARN (response: ${API_STATUS})"
    log "                 Check: docker compose logs api"
fi

log ""
log "============================================"
log " Sink installation complete!"
log "============================================"
log ""
log " Internal URL: http://127.0.0.1:${HOST_PORT}"
log " External URL: https://${DOMAIN}"
log ""
log " If this is the FIRST install, complete these steps:"
log ""
log "   1. Copy proxy config to the VPS reverse proxy:"
log "      cp ${SINK_DIR}/sink.conf /opt/infra/proxy/nginx/conf.d/"
log ""
log "   2. The wildcard cert for *.dev.marin.cr is already in place."
log "      No new certificate needed."
log ""
log "   3. Reload the VPS proxy:"
log "      docker exec proxy-nginx nginx -t"
log "      docker exec proxy-nginx nginx -s reload"
log ""
log "   4. Configure Google OAuth redirect URI:"
log "      https://${DOMAIN}/api/auth/google/callback"
log ""
log "   5. Verify:"
log "      curl https://${DOMAIN}/api/health/live"
log ""
log "============================================"
